### ISSUE TITLE
Impossible to cancel request with 'withDelegatingDispatchRequest'

### ISSUE THREAD

**Issue by spirylics** [ArcBees/gwtp-extensions#25]
Hi,

We can't cancel request in using withDelegatingDispatchRequest.

I think withDelegatingDispatchRequest should return the new delegate built and no this, because when execute method is invoked delegatingDispatchRequest is null.

Thanks,

**Comment by spirylics** [comment]
up

**Comment by olafleur** [comment]
@Chris-V could you take a look?

**Comment by Chris-V** [comment]
`withDelegatingDispatchRequest` returns the builder references because that's how fluent api calls work. The object you pass is a "delegate" and the internal references are updated when the REST end-point is called, then it is possible to use the passed object to cancel the call or check if it is pending.

**Comment by spirylics** [comment]
Sorry, I don't understand,

```java
DelegatingDispatchRequest request = new DelegatingDispatchRequest();

resource
  .withDelegatingDispatchRequest(dispatchRequest)
  .withCallback(new AsyncCallback<Void>() {...})
  .foo();

request.cancel();
```

should cancel foo request right ? because it doesn't work.

Extract from AbstractResourceDelegate.java

```java
    @Override
    public ResourceDelegate<T> withDelegatingDispatchRequest(DelegatingDispatchRequest delegatingDispatchRequest) {
        AbstractResourceDelegate<T> delegate = createCopy();
        delegate.delegatingDispatchRequest = delegatingDispatchRequest;

        return this;
    }
```

I don't see how delegate copy can be used.

**Comment by Chris-V** [comment]
Sorry. The method should indeed return `delegate` and not `this` so that the DispatchRequest configuration is preserved. Feel free to contribute a fix if you want to.

**Comment by spirylics** [comment]
Done : https://github.com/ArcBees/gwtp-extensions/pull/26
It's not a suggestion but a blocking bug.

GWTP and GWTP extensions are interessing but which is their future ? for example compared to errai ?

**Comment by christiangoudreau** [comment]
It is simple, take over Errai and the world! LOL I'm kidding :D

The goal of our framework has always been to be a "lightweight" framework to build your application. Errai for example, has a lot more functionalities than we will ever offer, because we want to give the choice to users as to what they want to use, while Errai, well, you need Java EE and a lot of interdependencies for each element you wish to use.

A new and more modern version of GWTP will come with GWT 3.0 where we want to offer an even more simple and lightweight version of our framework, while keeping the backward compatibility that we have kept until now.

**Comment by spirylics** [comment]
Ok, thanks for your reply and for your work with your team.
I use GWTP for a multiplatform project (cordova, polymer) and I always ask myself the question, which frameworks / libraries will be here in five years :)

**Comment by christiangoudreau** [comment]
One thing for sure, GWTP will still be around :D Most of our client are big corporation that invest on such technologies for at least 5 years :D
